# Generated by Django 6.0 on 2026-01-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("behind", "Behind"),
                            ("on_track", "On Track"),
                            ("ahead", "Ahead"),
                        ],
                        default="on_track",
                        max_length=10,
                    ),
                ),
                ("first_input", models.TextField()),
                ("second_input", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="goal.goal",
                    ),
                ),
            ],
        ),
    ]
